### ISSUE TITLE
预计开发的功能, 有建议也可以在下面提

### ISSUE THREAD

**Issue by guohuiyuan** [FloatTech/ZeroBot-Plugin-Webui#4]
- [x] job插件操作界面
- [ ] 删除好友和群聊的按钮
- [ ] 拿到gocq的cookie, 做qq空间表白墙的交互

**Comment by Stronglittleboy** [comment]
你好，免费苦力应征，有需要联系

**Comment by guohuiyuan** [comment]
> 你好，免费苦力应征，有需要联系

加qq群752669987, 写好入群备注
